#serverless.yml

service: my-express-application

plugins:
  - serverless-offline #serverless-offline needs to be last in the list

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  hello: 
    handler: index.handler
    events:
      - http:
          path: /cache-graphql
          method: get
  version: 
    handler: index.handler
    events:
      - http:
          path: /version
          method: get
  cacheQuery:
    handler: index.handler
    events:
      - http: 
          path: /cache-graphql
          method: post
          cors: true
