#serverless.yml

service: cache-server

plugins:
  - serverless-webpack
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'npm'


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  deploymentBucket:
    name: cache-serverless
    serverSideEncryption: AES256 # when using server-side encryption
  vpc:
    securityGroupIds:
      - sg-03990ed6d5e88c0b4
    subnetIds:
      - subnet-0f8b8c09d0dec367b


functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  version:
    handler: index.handler
    events:
     - http: 
          path: version
          method: get
  cacheQuery:
    handler: index.handler
    events:
      - http: 
          path: cache-graphql
          method: post
          cors: true

