#serverless.yml

service: cache-server

plugins:
  - serverless-webpack
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  tableName: 'cache-table-${self:provider.stage}'
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'npm'
  dynamodb:
    start:
      migrate: true
  

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  deploymentBucket:
    name: cache-serverless
    serverSideEncryption: AES256 # when using server-side encryption
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource:
        - { "Fn::GetAtt": ["CacheDynamoDBTable", "Arn" ] }
  vpc:
    securityGroupIds:
      - sg-03990ed6d5e88c0b4
    subnetIds:
      - subnet-c237a9a5

  environment:
    CACHE_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  cacheQuery:
    handler: index.handler
    events:
      - http: 
          path: cache-graphql
          method: post
          cors: true

  

resources:
  Resources:
    CacheDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: key
            AttributeType: S
        KeySchema:
          -
            AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
